### ISSUE TITLE
Should allow for more customization when messages are sent.

### ISSUE THREAD

**Issue by LeifAndersen** [racket/handin#29]
We want to modify the client so that it sends two usernames and passwords before the students can submit any code. We could just have the client concatinate the usernames before sending them, but then we run into the issue of passwords, which the client cannot just send concatinated, as we want to have an individual account for each student.

Another possibility would be to have the client send a list of strings, rather than just a single string. The server obviously will not be able to handle this without it being modified by hand. (Which I wouldn't be opposed to doing, but obviously this would unfortunately make an unneeded fork of the server.)

The hook function is fairly close to what I want, but it only gets called at the very end of the message, after the server has already dealt with everything. This is fine if I want to process extra data, but here I want to change the interpretation of the regular username data. I should be able to create a hook for that.

**Comment by elibarzilay** [comment]
I'm not following this.  The usual submission works with `+`-concatenated usernames and one of the passwords by design, to avoid students sharing passwords.  But this is unrelated to the hook functionality...  Are you trying to use the hook to do something outside of the handin server?

(Take this as a general comment, I don't have cycles to actually contribute code...)

**Comment by LeifAndersen** [comment]
Basically, I just want a mode that where the server requires everyone to type in there password, rather than only requiring one. I am submitting a PR that does this (well, partially, I still have to clean it up a bit before I'm comfortable merging it), so I'm going to close this issue.
